version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
  pre_build:
    commands:
      - echo "Installing Terraform..."
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/latest/terraform_latest_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - ls -l  # List files to verify bootstrap.sh is present and executable
      - terraform init
      - terraform --version
      - aws --version
  build:
    commands:
      - echo "Validating Terraform configuration..."
      - terraform validate
      - terraform plan -out=tfplan  # Generate the Terraform plan
      - |
        if [ $? -ne 0 ]; then
          echo "Terraform plan failed, exiting build..."
          exit 1  # Exit the build process if terraform plan fails
        fi
      - terraform apply -auto-approve tfplan  # Apply the Terraform plan if plan is successful
  post_build:
    commands:
      - echo "Checking the result of terraform apply..."
      - |
        if [ $? -ne 0 ]; then
          echo "Terraform apply failed."
          exit 1  # Exit with error to indicate failure, without destroying infrastructure
        else
          echo "Terraform apply succeeded."
        fi

