version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
  pre_build:
    commands:
      - echo "Installing Terraform..."
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - chmod +x bootstrap.sh  # Ensure bootstrap script is executable
      - ls -l  # List files to verify bootstrap.sh is present and executable
      - terraform init
      - terraform --version
      - aws --version
  build:
    commands:
      - echo "Validating Terraform configuration..."
      - terraform validate
      - terraform plan -out=tfplan  # Generate the Terraform plan
      - terraform apply -auto-approve tfplan  # Apply the Terraform plan
  post_build:
    commands:
      - echo "Checking the result of terraform apply..."
      - |
        if [ $? -ne 0 ]; then
          echo "Terraform apply failed, rolling back..."
          terraform destroy -auto-approve  # Trigger terraform destroy in case of failure
          exit 1  # Exit with error to indicate failure
        else
          echo "Terraform apply succeeded."
        fi

artifacts:
  files:
    - tfplan  # Store the plan as an artifact
    - terraform.tfstate
