version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
  build:
    commands:
      - echo "Applying Terraform changes using the stored plan..."
      - terraform apply tfplan || (echo "Terraform apply failed. Running Terraform destroy..." && terraform destroy -auto-approve)

  post_build:
    commands:
      - echo "Terraform apply completed successfully or was rolled back due to an error."
