version: 0.2

phases:
  install:
    runtime-versions:
      python: latest

  build:
    commands:
      - echo "Running Terraform destroy to clean up resources..."
      - terraform destroy -auto-approve

  post_build:
    commands:
      - echo "Terraform resources have been destroyed successfully."
